### ISSUE TITLE
File Linking!

### ISSUE THREAD

**Issue by azazelyash** [KAMYAVERMA/COACHING-CLASSES#1]
Kamya isme files ke linking me thodi problem hai, ig tum apne system me banayi thi to reference url me exact path add ki hogi.
But agar kisi aor ke system me open karogi to css ya js load nhi lega...
So, if possible then saare object, images, aor files ka location change karke exact path ki jagah, relative path likh do, to fix ho jayega.
I mean instead of ## C:/cde/abc/file_name.xyz## ki jagah bs ##../file_name.xyz##

**Comment by KAMYAVERMA** [comment]
Hnn...ok ok....
Thanku.....krti hu main...!!!
